BOOST_INC_DIR = ['C:\\Users\\Eracoy\\Anaconda2\\pkgs\\libboost-1.67.0-hfd51bdf_4\\Library\\include\\boost']
BOOST_LIB_DIR = ['C:\\Users\\Eracoy\\Anaconda2\\pkgs\\libboost-1.67.0-hfd51bdf_4\\Library\\include\\boost']
BOOST_COMPILER = 'gcc43'
USE_SHIPPED_BOOST = False
BOOST_PYTHON_LIBNAME = ['boost_python-py37']
BOOST_THREAD_LIBNAME = ['boost_thread']
CUDA_TRACE = False
CUDA_ROOT = 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1'
CUDA_ENABLE_GL = True
CUDA_ENABLE_CURAND = True
CUDADRV_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib/x64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib/x64/stubs']
CUDADRV_LIBNAME = ['cuda']
CUDART_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib/x64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib/x64/stubs']
CUDART_LIBNAME = ['cudart']
CURAND_LIB_DIR = ['${CUDA_ROOT}/lib', '${CUDA_ROOT}/lib/x64', '${CUDA_ROOT}/lib/stubs', '${CUDA_ROOT}/lib/x64/stubs']
CURAND_LIBNAME = ['curand']
CXXFLAGS = ['/EHsc']
LDFLAGS = ['/FORCE']
